INCLUDE(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1.7)

CMAKE_FORCE_C_COMPILER(dcpu16-clang clang)
CMAKE_FORCE_CXX_COMPILER(dcpu16-clang clang)
SET(CMAKE_ASM_COMPILER dcpu16-as)

SET(CMAKE_C_FLAGS_INIT "-S -nostdinc")

SET(CMAKE_FIND_ROOT_PATH ./)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NENVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_path_MODE_INCLUDE ONLY)

